---
- hosts: localhost 
  become: true
  tasks:
     - name: stop previous version docker
       shell: docker stop kiran_demo
     - name: remove stopped container
       shell: docker rm -f kiran_demo
     - name: remove docker images
       shell: docker image rm -f justkiran/justkiran:kiran_demo
       
     - name: create docker image
       shell: docker run -d --name kiran_demo -p 8090:8080 justkiran/justkiran:kiran_demo
